import React from 'react';
import Head from 'next/head';

import Navbar from './Navbar';
import Footer from './Footer';

const Layout = ({ children }) => {
  return (
    <div className='layout'>
      <Head>
        <title>Rotondaro's Store</title>
        <header>
          <Navbar />
        </header>
        <main className='main-conteiner'>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
        {/* <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' /> */}
      </Head>
    </div>
  );
};

export default Layout;
